### ISSUE TITLE
关于mweb的有序标题序号的优化建议

### ISSUE THREAD

**Issue by lee528066** [oulvhai/MWeb-issues#1125]
![image](https://user-images.githubusercontent.com/22288152/46253377-c7c81e00-c4ac-11e8-8e76-6d3468817c9f.png)
1. 编辑窗口和预览窗口的有序标题，序号是否支持同步。
2. 在有序标题下插入代码块后，有序序号排序会重置成从1开始。（虽然是markdown原生语法的特性，但是能够优化成连续的序号显示，其他的笔记产品都做过优化，例如：bear、typora、有道云笔记等等。）

**Comment by lee528066** [comment]
版本号：3.1.6（440）

**Comment by hitzhangjie** [comment]
这个其实很简单就能实现了，自己喜欢的preview theme里面添加如下css代码就可以了：

```css
body {
    counter-reset: h1
}

h1 {
    counter-reset: h2
}

h2 {
    counter-reset: h3
}

h3 {
    counter-reset: h4
}

h4 {
    counter-reset: h5
}

h5 {
    counter-reset: h6
}

h1:before {
    counter-increment: h1;
    content: counter(h1) ". "
}

h2:before {
    counter-increment: h2;
    content: counter(h1) "." counter(h2) ". "
}

h3:before {
    counter-increment: h3;
    content: counter(h1) "." counter(h2) "." counter(h3) ". "
}

h4:before {
    counter-increment: h4;
    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) ". "
}

h5:before {
    counter-increment: h5;
    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5)
}

h6:before {
    counter-increment: h6;
        content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) "." counter(h6) ". "
}
```
